### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by moshe** [moshe/elasticsearch-comrade#11]
### makeup
- [x] Shards Grid: Fix square colors

### Tasks
- [x] combobox should close after selection

### Aliases
- [ ] Do not suggest already added alias in the alias dropdown
- [ ]  Suggest not committed aliases in the drop down

### Grid
- [x]  Index Cell alignment
- [x] Index pagination
- [ ]  Disable node selection if primary/replica selected is already on that node
- [x] Add count of uninitialized shards in the cluster view
- [x] Check 3 digit shards
- [ ] Show abs numbers in node metrics

### REST
- [x] Cmd + Enter to run query

### Docs
- [x] https://themes.gohugo.io//theme/hugo-theme-learn/en/basics/installation/

### Build
- [x] https://github.com/siddharthkp/bundlesize

### Snapshots
- [ ] Check create a snapshot and restore
